import Head from 'next/head';
import Image from 'next/image';
import classnames from 'classnames';
import { useRef, useState } from 'react';
import { Parallax, ParallaxLayer } from '@react-spring/parallax';
import { useSpring, animated } from '@react-spring/web';

export default function Home() {
  const parallax = useRef(null);
  const [hideShowcase, setHideShowcase] = useState(false);

  const showcaseSpring = useSpring({
    left: hideShowcase ? '-100%' : '0',
  });

  const detailSpring = useSpring({
    left: hideShowcase ? '0%' : '100%',
  });

  const handleViewClick = (section) => {
    console.log(section);
    setHideShowcase(!hideShowcase);
  };

  return (
    <div>
      <Head>
        <title>Lindsey Erstad's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="page-wrapper">
          <animated.div className="animation-container" style={showcaseSpring}>
            <div className="showcase-container">
              <Parallax className="parallax" ref={parallax} pages={7}>
                <ParallaxLayer cardName="about-section">
                  <div className="container">
                    <h1 className="headline">Hello, I'm Lindsey!</h1>
                    <h3 className="subhead">
                      I design&nbsp;
                      <span className="subhead-accent">UX/UI</span>
                      &nbsp;and&nbsp;
                      <span className="subhead-accent">Graphic</span> solutions.
                    </h3>
                  </div>
                </ParallaxLayer>

                {/** Fruit Stand Section */}
                <ParallaxLayer className="card dark" sticky={{ start: 1, end: 4 }}>
                  <div className="content">
                    <div className="content-container right">
                      <h2 className="heading">MY FRUIT STAND</h2>
                      <h3 className="subhead">Game Prototype</h3>
                      <button
                        onClick={() => {
                          handleViewClick('shopkeep');
                        }}
                        className="link"
                      >
                        View Work
                      </button>
                    </div>
                  </div>
                </ParallaxLayer>
                <ParallaxLayer className="parallax-image-layer" sticky={{ start: 1, end: 4 }}>
                  <div className="fruit-stand-image tile-1 image-tile"> t1 </div>
                </ParallaxLayer>
                <ParallaxLayer className="parallax-image-layer" sticky={{ start: 1, end: 4 }}>
                  <div className="fruit-stand-image tile-2 image-tile"> t2 </div>
                </ParallaxLayer>
                {/** End Fruit Stand Section */}
                {/** Shopkeep Section */}
                <ParallaxLayer className="card light" sticky={{ start: 4, end: 4 }}>
                  <div className="content">
                    <div className="content-container left">
                      <h2 className="heading">SHOPKEEP</h2>
                      <h3 className="subhead">App Concept</h3>
                      <button
                        onClick={() => {
                          handleViewClick('shopkeep');
                        }}
                        className="link"
                      >
                        View Work
                      </button>
                    </div>
                  </div>
                </ParallaxLayer>
                <ParallaxLayer className="shopkeep-image tile-1 image-tile" sticky={{ start: 4, end: 4 }}>
                  <div> t1 </div>
                </ParallaxLayer>
                <ParallaxLayer className="shopkeep-image tile-2 image-tile" sticky={{ start: 4, end: 4 }}>
                  <div> t2 </div>
                </ParallaxLayer>
                <ParallaxLayer className="shopkeep-image tile-3 image-tile" sticky={{ start: 4, end: 4 }}>
                  <div> t3 </div>
                </ParallaxLayer>
                {/** End Shopkeep Section */}
              </Parallax>
            </div>
          </animated.div>
          <animated.div className="animation-container details" style={detailSpring}>
            <div className="details-container">
              <button
                onClick={() => {
                  handleViewClick();
                }}
              >
                Content
              </button>
            </div>
          </animated.div>
        </div>
      </main>
    </div>
  );
}
